// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rafdekar/speedtest/api/provider (interfaces: Provider)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// GetDownloadSpeed mocks base method.
func (m *MockProvider) GetDownloadSpeed() float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDownloadSpeed")
	ret0, _ := ret[0].(float64)
	return ret0
}

// GetDownloadSpeed indicates an expected call of GetDownloadSpeed.
func (mr *MockProviderMockRecorder) GetDownloadSpeed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDownloadSpeed", reflect.TypeOf((*MockProvider)(nil).GetDownloadSpeed))
}

// GetUploadSpeed mocks base method.
func (m *MockProvider) GetUploadSpeed() float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUploadSpeed")
	ret0, _ := ret[0].(float64)
	return ret0
}

// GetUploadSpeed indicates an expected call of GetUploadSpeed.
func (mr *MockProviderMockRecorder) GetUploadSpeed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUploadSpeed", reflect.TypeOf((*MockProvider)(nil).GetUploadSpeed))
}

// Init mocks base method.
func (m *MockProvider) Init() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init")
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockProviderMockRecorder) Init() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockProvider)(nil).Init))
}
